version: "3.4"

services:
  db:
    image: postgres:10
    ports:
      - "5432:5432"
  api:
    build: ./api
    command: yarn start:dev
    volumes:
      - ./api/src:/app/src
      - ./api/tslint.json:/app/tslint.json
      - ./api/tsconfig.json:/app/tsconfig.json
      - ./api/nodemon.json:/app/nodemon.json
      - ./api/prettierrc:/app/prettierrc
    ports:
      - "8080:8080"
    environment:
      - FRONTEND_URL=http://localhost:8080
      - DEBUG=true
    env_file:
      - .env

volumes:
  db-data: {}
